
name: Auto Deploy Project When Push Main Branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      #- name: Git User Settings
      #  run: |
      #    git config --local user.email "qkstjr09@gmail.com"
      #    git config --local user.name "jpark6"
      
      - name: Dependencies
        run: yarn install
        
      - name: Deploy
        env:
          GH_API_KEY: ${{ secrets.ACCESS_TOKEN }}
        run: yarn run deploy
